# Generated by Django 2.1.7 on 2019-03-09 20:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import website.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('website', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBlog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('embed', website.blocks.Embed())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
