# Generated by Django 2.1.7 on 2019-03-14 16:01

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190314_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingupdate',
            name='update_type',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liveblog',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('message_id', wagtail.core.blocks.CharBlock()), ('timestamp', wagtail.core.blocks.DateTimeBlock()), ('message', wagtail.core.blocks.CharBlock())]))], blank=True),
        ),
    ]
