# Generated by Django 2.1.7 on 2019-03-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190314_1728'),
        ('website', '0007_auto_20190314_1806'),
    ]

    operations = [
    ]
