# Generated by Django 2.1.7 on 2019-03-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_store-original-message-as-json'),
        ('website', '0010_auto_20190316_1141'),
    ]

    operations = [
    ]
